### ISSUE TITLE
bhop server Third Person Glitch

### ISSUE THREAD

**Issue by DiniOG** [busheezy/JoshOG-Servers#11]
Players have been abusing this. It isn't too bad I guess, but what they do is go in third person, go in console and type "firstperson" then complete it that way.http://i.imgur.com/hBi11bv.jpg (screenshot says 3rd person but I am in First person)

**Comment by Technoblazed** [comment]
Will be investigated and corrected if possible. Else third person temporarily removed until a fix is found.

**Comment by Technoblazed** [comment]
Third person removed from the servers as this is unable to be removed.
