### ISSUE TITLE
Surf Tier 1-2 Map Request

### ISSUE THREAD

**Issue by xdERP** [busheezy/JoshOG-Servers#12]
Tier 1 Linear  surf_funhouse_njv - 
http://fastdl.gflclan.com/csgo/maps/surf_funhouse_njv.bsp.bz2
Tier 1 Linear  surf_lavaflow -
 http://fastdl.gflclan.com/csgo/maps/surf_lavaflow.bsp.bz2
Tier 1 Staged  surf_how2surf - 
http://fastdl.gflclan.com/csgo/maps/surf_how2surf.bsp.bz2
Tier 1 Staged  surf_mom - 
http://fastdl.gflclan.com/csgo/maps/surf_mom.bsp.bz2
Tier 1 Staged  surf_prime_time_r3vamp - http://fastdl.gflclan.com/csgo/maps/surf_prime_time_r3vamp.bsp.bz2
Tier 1 Staged  surf_singletons - 
http://fastdl.gflclan.com/csgo/maps/surf_singletons.bsp.bz2

**Comment by Technoblazed** [comment]
Link submitted to be added to FastDL.

**Comment by Technoblazed** [comment]
surf_funhouse_njv
surf_lavaflow
surf_how2surf 
surf_mom

Added to the server and map lists. Remaining maps are too large and/or cause crashes.
