### ISSUE TITLE
T1-2 Surf Map Request

### ISSUE THREAD

**Issue by HunterTheFox** [busheezy/JoshOG-Servers#15]
surf_juturna would be a great map to add. It has a bonus as well

**Comment by Technoblazed** [comment]
Map uploaded to server and confirmed working. Requesting @busheezy to add to the FastDL: http://dl.technoblazed.xyz/surf/maps/surf_juturna.bsp.bz2 .

Will be zoned later today for release tonight.

**Comment by Technoblazed** [comment]
Map has been added and zoned. Issue closed.
