### ISSUE TITLE
Surf 1-2 !back reset to stage one

### ISSUE THREAD

**Issue by kittenslut** [busheezy/JoshOG-Servers#16]
Doing /back and !back on any stage will return you to stage 1.
This was tested on map surf_syria and surf_spacejam but i don't believe this is map related. I also record how to do it if you need to see it.
Recreate steps:
Beat at least 2 stages then do !spec on someone then do !back or /back

Posted 2/4/2016 =^~^=

**Comment by Technoblazed** [comment]
Unrepeatable so can only presume that the problem is solved.
