### ISSUE TITLE
2 bhop server suggestions

### ISSUE THREAD

**Issue by DiniOG** [busheezy/JoshOG-Servers#17]
# First suggestion:

A few members wanted me to suggest this for the bhop server. They are wanting a world record sound for whenever someone beats the current WR. Of course it would have to be disabled at the beginning of new maps so it doesn't get spammed the entire time. Just a small suggestion :)

# Second suggestion:

This suggestion was also requested by a few people in the bhop server. They are wanting a "currently spectating" which is on the surf server (on left side), though is not on the bhop server.

# Third suggestion:

Add !flashlight? Most maps are dark and hard to see.

**Comment by Technoblazed** [comment]
Your first suggestion is currently unavailable at this time and may not be used to due to the large amount of WR's that will be available to beat in the upcoming week.

The second suggestion has now been implemented and now appears on the maps.

The third suggestion now has !flashlight implemented.
