### ISSUE TITLE
bhop server time issue

### ISSUE THREAD

**Issue by DiniOG** [busheezy/JoshOG-Servers#21]
A player is having an issue with getting times. He finishes the map and it does not show up in the chat or in the hud for him. He tried other ranked styles, but still nothing.

http://steamcommunity.com/id/IAbooseBabies/

His account is fairly new so maybe? I'm not sure.

**Comment by Technoblazed** [comment]
His account has been automatically banned from the server for scripting. This is an automatic detection feature.
