### ISSUE TITLE
Make it so !call doesn't show in global chat

### ISSUE THREAD

**Issue by niofalpha** [busheezy/JoshOG-Servers#25]
If you're playing and someone's hacking and they see you type !call they're obviously gonna toggle off. It's stupid how it gets displayed in game.

**Comment by Technoblazed** [comment]
An alternative to this is to use /call. This will not be displayed on the server chat. This message will be amended shortly.

**Comment by Technoblazed** [comment]
Alternative method put in place. Please use /call
