### ISSUE TITLE
bhop_troipic_v2_csgo_fix end zone is too low

### ISSUE THREAD

**Issue by kittenslut** [busheezy/JoshOG-Servers#27]
The end zone is too low vs the player spawn point(Trigger), so when you beat the map you'll spawn like 5ft above the end zone and if you were b hopping before you teleport you will go flying out.
https://gyazo.com/c7b5b37863ad6315d2d411635e1a7f4b
The green box is where it should go up to the end zone, red dot spawn point.

So pretty much make end zone bigger or raise it :)

**Comment by Technoblazed** [comment]
Map zones redone.
