### ISSUE TITLE
[FAO Bush] Do this plox. <3

### ISSUE THREAD

**Issue by Technoblazed** [busheezy/JoshOG-Servers#3]
-  surf_2012 added to FastDL - http://technoblazed.xyz/private/surf_2012_beta12.bsp.bz2 
-  dis map added to fastdl - http://technoblazed.xyz/private/surf_windrunner_final.bsp.bz2
-  Server map cycles: http://technoblazed.xyz/private/surf1-2.zip 
-  http://technoblazed.xyz/private/surf3-6.zip

**Comment by busheezy** [comment]
Done.  Also, It's umc_mapcycle not umc-mapcycle.
