### ISSUE TITLE
{1v1 Severs but probably on all of them} Censor plugin

### ISSUE THREAD

**Issue by ILack** [busheezy/JoshOG-Servers#36]
So I said a blacklisted word and i muted and gagged me for what it said for 60 seconds, but after that 60 seconds I couldn't talk. Still was muted and gagged, even tried to go on other servers but the ban list seems to apply to all servers. Fix pls.

**Comment by ILack** [comment]
Forgot to mention, didn't know this was implemented until today, obviously, but I was pretty sure it wasn't on the servers until today. :\

**Comment by Technoblazed** [comment]
Added on steam to inform.
