### ISSUE TITLE
Minigame Maps 

### ISSUE THREAD

**Issue by MrFoo0** [busheezy/JoshOG-Servers#8]
Map to be removed : 
mg_krane_multigames

Maps to be added : 
mg_sonic_multigames http://csgo.gamebanana.com/maps/download/180190

mg_nature_multigames_v2 http://csgo.gamebanana.com/maps/download/187127

mg_gruber_multigames http://csgo.gamebanana.com/maps/download/186874

mg_hype2_v2a http://csgo.gamebanana.com/maps/download/188928 

Backup Map :
mg_wl_multigames_csgo_v1 http://csgo.gamebanana.com/maps/185389

**Comment by Technoblazed** [comment]
-   Maps added to FastDL.
-   Maps tested and added to servers.
-   umc_mapcycles edited.
